version: '3.9'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0rc2
    ports:
      - "5001:5000"
    command: >
      mlflow server
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
        --host 0.0.0.0
    volumes:
      - mlflow-artifacts:/mlflow/artifacts
      - mlflow-db:/mlflow

volumes:
  mlflow-artifacts:
  mlflow-db: